import {
  faSolidArrowRight,
  faSolidArrowRightFromBracket,
  faSolidBars,
  faSolidBoxesPacking,
  faSolidChartBar,
  faSolidChevronDown,
  faSolidChevronUp,
  faSolidCircle,
  faSolidClock,
  faSolidCow,
  faSolidEllipsisVertical,
  faSolidFeather,
  faSolidGlobe,
  faSolidHouse,
  faSolidLeaf,
  faSolidListCheck,
  faSolidMoon,
  faSolidPlus,
  faSolidRectangleXmark,
  faSolidSun,
  faSolidTractor,
  faSolidTriangleExclamation,
  faSolidUser,
  faSolidUsers,
  faSolidXmark,
} from '@ng-icons/font-awesome/solid';

/**
 * App-wide icon set for ng-icons. Only icons that are actually used in templates
 * are registered to keep bundle size minimal.
 */
export const APP_ICONS = {
  faSolidArrowRight,
  faSolidArrowRightFromBracket,
  faSolidBars,
  faSolidBoxesPacking,
  faSolidChartBar,
  faSolidChevronDown,
  faSolidChevronUp,
  faSolidCircle,
  faSolidClock,
  faSolidCow,
  faSolidEllipsisVertical,
  faSolidFeather,
  faSolidGlobe,
  faSolidHouse,
  faSolidLeaf,
  faSolidListCheck,
  faSolidMoon,
  faSolidPlus,
  faSolidRectangleXmark,
  faSolidSun,
  faSolidTractor,
  faSolidTriangleExclamation,
  faSolidUser,
  faSolidUsers,
  faSolidXmark,
};
